using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Tower : MonoBehaviour
{

    [SerializeField] float range = 3.0f;
    [SerializeField] Projectile projectile;
    [SerializeField] Transform firingPoint;

    // Enemy bookkeeping
    [SerializeField] LayerMask enemyLayers;
    [SerializeField] Collider[] colliders;
    [SerializeField] List<Enemy> enemiesInRange;
    [SerializeField] Enemy targetedEnemy;

    private void Update()
    {
        // == SCANNING PART ==

       // Find the surrounding colliders, only detect objects on enemy layer
       colliders = Physics.OverlapSphere(transform.position, range, enemyLayers);

        // Clear the list first
        enemiesInRange.Clear();

        // Go over each of the detected colliders
        foreach(Collider collider in colliders)
        {
            enemiesInRange.Add(collider.GetComponent<Enemy>());
        }

        // If there are enemies in range, pick one to target
        if(enemiesInRange.Count != 0)
        {
            targetedEnemy = enemiesInRange[0];
        }

        // == FIRING PART ==

        // make sure there is something to shoot at
        if(targetedEnemy != null)
        {
            // get enemy direction relative to the tower
            Vector3 enemyDirection 
                = (targetedEnemy.transform.position - firingPoint.position).normalized;
            
            
            // create and setup a projectile
            Instantiate(projectile, firingPoint.position, Quaternion.identity)
                .Setup(enemyDirection);
        }


    }


    private void OnDrawGizmosSelected()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, range);
    }
}
